[2020-04-08 00:55:04,185] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data07.insert_csv_sample 2020-04-07T00:00:00+00:00 [queued]>
[2020-04-08 00:55:04,193] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data07.insert_csv_sample 2020-04-07T00:00:00+00:00 [queued]>
[2020-04-08 00:55:04,194] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-08 00:55:04,194] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-04-08 00:55:04,194] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-08 00:55:04,199] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): insert_csv_sample> on 2020-04-07T00:00:00+00:00
[2020-04-08 00:55:04,201] {standard_task_runner.py:53} INFO - Started process 79575 to run task
[2020-04-08 00:55:04,248] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atp_data07.insert_csv_sample 2020-04-07T00:00:00+00:00 [running]> zipcodes-MacBook-Pro-4.local
[2020-04-08 00:55:04,267] {taskinstance.py:1128} ERROR - extra data after last expected column
CONTEXT:  COPY sample, line 1: "0,1461,169277.0524984"
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/cchavez/dev/airflow_home/dags/atp_data07.py", line 70, in insert_csv_sample
    cur.copy_from(f, 'sample', sep=',')
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY sample, line 1: "0,1461,169277.0524984"

[2020-04-08 00:55:04,270] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=atp_data07, task_id=insert_csv_sample, execution_date=20200407T000000, start_date=20200408T045504, end_date=20200408T045504
[2020-04-08 00:55:14,144] {logging_mixin.py:112} INFO - [2020-04-08 00:55:14,144] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-04-08 02:34:12,266] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data07.insert_csv_sample 2020-04-07T00:00:00+00:00 [queued]>
[2020-04-08 02:34:12,275] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data07.insert_csv_sample 2020-04-07T00:00:00+00:00 [queued]>
[2020-04-08 02:34:12,275] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-08 02:34:12,275] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-04-08 02:34:12,275] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-08 02:34:12,281] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): insert_csv_sample> on 2020-04-07T00:00:00+00:00
[2020-04-08 02:34:12,282] {standard_task_runner.py:53} INFO - Started process 81513 to run task
[2020-04-08 02:34:12,330] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atp_data07.insert_csv_sample 2020-04-07T00:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-04-08 02:34:12,366] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-04-08 02:34:12,373] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=atp_data07, task_id=insert_csv_sample, execution_date=20200407T000000, start_date=20200408T063412, end_date=20200408T063412
[2020-04-08 02:34:22,224] {logging_mixin.py:112} INFO - [2020-04-08 02:34:22,223] {local_task_job.py:103} INFO - Task exited with return code 0
